name: Deploy QA (GitHub Pages) on qa tags

on:
  push:
    tags:
      - "qa"
      - "qa-*"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages-qa"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: workflow-ui/package-lock.json

      - name: Install dependencies
        working-directory: workflow-ui
        run: npm ci

      - name: Build (with repo base for GitHub Pages)
        working-directory: workflow-ui
        run: npm run build -- --base=/${{ github.event.repository.name }}/

      - name: Upload Pages artifact (workflow-ui/dist)
        uses: actions/upload-pages-artifact@v3
        with:
          path: workflow-ui/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: qa
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4


